version: '3.8'
services:
  auth-service:
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - USER_SERVICE_M2M_TOKEN=${USER_SERVICE_M2M_TOKEN}
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "8082:8080"
    networks:
      - clearpass-net

  user-service:
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - USER_SERVICE_M2M_TOKEN=${USER_SERVICE_M2M_TOKEN}
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - clearpass-net

  asset-service:
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - USER_SERVICE_M2M_TOKEN=${USER_SERVICE_M2M_TOKEN}
      - USER_SERVICE_URL=http://user-service:8081
    build:
      context: .
      dockerfile: services/asset-service/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service
    networks:
      - clearpass-net

networks:
  clearpass-net:
    driver: bridge
